### PR TITLE
Make consitent with develop

### PR DESCRIPTION
**Pull request by kamilsa**
This PR makes documentation consistent with develop

### CODE REVIEW

**Comment by l4l** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[source/includes/_cli.md, line 14 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyVxI6NtDAlLNCdLnH5:-KyVxI6NtDAlLNCdLnH6:b-fw0vl5) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_cli.md#L14)):*
> from which

just _where_ is better

---

*[source/includes/_commands.md, line 490 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyVy7YbKl9i8aP0vuON:-KyVy7YbKl9i8aP0vuOO:bjbxtye) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_commands.md#L490)):*
> belongs to the set of existing permissions

just _are defined_

---

*[source/includes/_commands.md, line 526 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyVyFsKvJYzrPdhzHfd:-KyVyFsKvJYzrPdhzHfe:bb7od0r) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_commands.md#L526)):*
> ```Markdown
> -------------- | -------------- | --------------
> Account ID | id of account whom rights were granted | should be existent in the system
> Permission name | name of revoked permission | permission belongs to the set of existing permissions
> ```

same

---

*[source/includes/_queries.md, line 113 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyVyR-C55e7plY7vkOw:-KyVyR-C55e7plY7vkOx:b15wm69) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_queries.md#L113)):*
> subset of existing permissions

this is enforced by the `Permission` message itself, isn't it?

---

*[source/includes/_run.md, line 5 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyVzOuqOCOgVHW1aJM6:-KyVzOuqOCOgVHW1aJM7:b-hmdima) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_run.md#L5)):*
> ```Markdown
> ## Generate genesis block
> 
> 1. Create peers.list file containing the peers' addresses. For the local node suffice to add only single peer: `bash $ echo 'localhost:10001' > peers.list`
> ```

Split that in two lines

---

*[source/includes/_run.md, line 7 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyVzR0Yl4UPavOtPFoD:-KyVzR0Yl4UPavOtPFoE:buo9nmt) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_run.md#L7)):*
> ```Markdown
> 1. Create peers.list file containing the peers' addresses. For the local node suffice to add only single peer: `bash $ echo 'localhost:10001' > peers.list`
> 
> 2. Generate genesis block using iroha-cli: `bash $ iroha-cli --genesis_block --peers_address peers.list` File genesis.block with keypair files for Administrator account (`admin@test.priv` and `admin@test.pub`) and node (`node0.priv` and `node0.pub`) should be generated in the same folder.
> ```

Same here

---

*[source/includes/_run.md, line 9 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyVzWuMIWpE_OqaYyB-:-KyVzWuMIWpE_OqaYyB0:b-1q364m) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_run.md#L9)):*
> ```Markdown
> 2. Generate genesis block using iroha-cli: `bash $ iroha-cli --genesis_block --peers_address peers.list` File genesis.block with keypair files for Administrator account (`admin@test.priv` and `admin@test.pub`) and node (`node0.priv` and `node0.pub`) should be generated in the same folder.
> 
> Pass generated genesis block to irohad using --genesis_block flag.
> ```

Example?

---

*[source/includes/_run.md, line 48 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyVzi-BeLhd_WFfqMGo:-KyVzi-BeLhd_WFfqMGp:b-te8qe5) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_run.md#L48)):*
> are to be

fix that as well

---

*[source/includes/_run.md, line 54 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyW-YIVXiYQ1VLdDkIS:-KyW-YIVXiYQ1VLdDkIT:bemputi) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_run.md#L54)):*
> ```Markdown
> | config        | configuration file, containing postgres, and redis connection, and values to tune the system |
> | genesis_block | initial block in the ledger                                                                  |
> | keypair_name  | private and public key, which is used by peer to sign the blocks                             |
> ```

Note also, that should be passed w/o extension suffix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha-api/21)*

**Comment by kamilsa** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[source/includes/_queries.md, line 113 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyVyR-C55e7plY7vkOw:-KyW6GN-J_XzRTgqntPb:b-i4npyt) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_queries.md#L113)):*
<details><summary><i>Previously, l4l (Eugene) wrote…</i></summary><blockquote>

> subset of existing permissions

this is enforced by the `Permission` message itself, isn't it?
</blockquote></details>

Using that logic we don't need to put constraints to responses

---

*[source/includes/_run.md, line 9 at r1](https://reviewable.io:443/reviews/hyperledger/iroha-api/21#-KyVzWuMIWpE_OqaYyB-:-KyW987paCJuTxA66R12:b-y2nru4) ([raw file](https://github.com/hyperledger/iroha-api/blob/1f32fbd12fea28b3e9281be6748903d004a8861c/source/includes/_run.md#L9)):*
<details><summary><i>Previously, l4l (Eugene) wrote…</i></summary><blockquote>

Example?
</blockquote></details>

Better to remove this line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha-api/21)*

**Comment by l4l** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha-api/21)*

**Review by l4l — APPROVED** [review]

**Review by neewy — APPROVED** [review]

**Comment by neewy** [comment]
Seems that I merged code manually, please check

**Pull request closed without merging**
